---
language: ruby

bundler_args: --without system_tests

rvm:
  - 1.9.3

env:
  - PUPPET_VERSION = 3.1.1

script: 'bundle exec rake validate && bundle exec rake lint'

notifications:
  email: false
