---
language: ruby

bundler_args: --without system_tests

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1

script: 'bundle exec rake validate && bundle exec rake lint'

notifications:
  email: false
